# Generated by Django 5.2.4 on 2025-08-15 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_chatmessage_deleted_by_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.chatmessage'),
        ),
    ]
