# Generated by Django 5.2.4 on 2025-08-25 22:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_chatroommute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='avatars/default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
